/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import Estructuras.Cola;
import Estructuras.Generic;
import Estructuras.Lista;
import Estructuras.Nodo;
import Estructuras.Pila;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick
 */
public class Menu_carga extends javax.swing.JFrame {

    /**
     * Creates new form Menu_inicio
     */
    public JFileChooser seleccion;
    public static String path;
    public File archivo;
    public FileReader fr;
    public  BufferedReader br;
    
    public static int no_suelo=0;
    public static int no_pared=0;
    public static int no_goomba=0;
    public static int no_koopa=0;
    public static int no_ficha=0;
    public static int no_hongo=0;
    public static int no_personaje=0;
    public static int no_castillo=0;
    public static Lista lista_objetos =new Lista();
    public Generic objeto_nuevo;
    public static int tipo_extraccion=0;
    public static Pila pila_resultante;
    public static Cola cola_resultante;
    public static Tablero tablero =new Tablero();
    public Generic seleccionado;
    public int posicion_x;
    public int posicion_y;
    //1 cola tipo_extraccion
    //0 Pila tipo_extraccion
    
    
    
    public Menu_carga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        tablero2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Imagen_prueba = new javax.swing.JLabel();
        boton_continuar = new javax.swing.JButton();
        seleccion_pila = new javax.swing.JRadioButton();
        seleccion_cola = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel_muestra1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel_muestra = new javax.swing.JPanel();
        JPanel_grafica = new javax.swing.JPanel();
        label_grafo = new javax.swing.JLabel();
        boton_graficar = new javax.swing.JButton();
        boton_agregar_objeto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_path_imagen = new javax.swing.JTextField();
        boton_path_imagen1 = new javax.swing.JButton();
        txt_nombre_objeto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lista_tipo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_mostrador = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boton_borrar = new javax.swing.JButton();
        boton_editar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        label_modo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_tablero = new javax.swing.JPanel();
        label_tipo = new javax.swing.JLabel();
        nombre_objeto = new javax.swing.JLabel();
        boton_grafo_lista = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_no_columnas = new javax.swing.JLabel();
        label_no_filas = new javax.swing.JLabel();
        boton_add_fila = new javax.swing.JButton();
        boton_add_columna = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_fila_actual = new javax.swing.JLabel();
        label_columna_actual = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mario Maker Guatemalteco v.1.0.0");
        getContentPane().setLayout(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 220, 120, 40);
        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(350, -30, 100, 100);

        tablero2.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel6.setText("Vista Previa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 120, 130, 20);

        Imagen_prueba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen_pruebaMouseClicked(evt);
            }
        });
        Imagen_prueba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Imagen_pruebaKeyPressed(evt);
            }
        });
        jPanel1.add(Imagen_prueba);
        Imagen_prueba.setBounds(160, 10, 180, 110);

        boton_continuar.setText("Continuar");
        boton_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_continuarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_continuar);
        boton_continuar.setBounds(210, 173, 120, 40);

        seleccion_pila.setSelected(true);
        seleccion_pila.setText("Pila");
        seleccion_pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion_pilaActionPerformed(evt);
            }
        });
        jPanel1.add(seleccion_pila);
        seleccion_pila.setBounds(30, 140, 120, 30);

        seleccion_cola.setText("Cola");
        seleccion_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion_colaActionPerformed(evt);
            }
        });
        jPanel1.add(seleccion_cola);
        seleccion_cola.setBounds(30, 180, 130, 30);

        jLabel7.setText("Elija tipo de Extracción");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 100, 150, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(490, 20, 360, 220);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Panel_muestra1.setLayout(null);

        jLabel8.setText("Nombre");
        Panel_muestra1.add(jLabel8);
        jLabel8.setBounds(30, 70, 90, 30);

        jLabel9.setText("Path");
        Panel_muestra1.add(jLabel9);
        jLabel9.setBounds(140, 70, 220, 30);

        jLabel10.setText("Imagen");
        Panel_muestra1.add(jLabel10);
        jLabel10.setBounds(360, 70, 110, 30);

        jLabel11.setText("Tipo");
        Panel_muestra1.add(jLabel11);
        jLabel11.setBounds(520, 70, 100, 30);

        Panel_muestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_muestra1.add(Panel_muestra);
        Panel_muestra.setBounds(20, 110, 720, 320);

        jScrollPane1.setViewportView(Panel_muestra1);

        jTabbedPane1.addTab("Lista", jScrollPane1);

        JPanel_grafica.setLayout(null);
        JPanel_grafica.add(label_grafo);
        label_grafo.setBounds(10, 50, 790, 340);

        boton_graficar.setText("Gráficar");
        boton_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_graficarActionPerformed(evt);
            }
        });
        JPanel_grafica.add(boton_graficar);
        boton_graficar.setBounds(10, 10, 130, 30);

        jTabbedPane1.addTab("Gráfica", JPanel_grafica);

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 240, 810, 430);

        boton_agregar_objeto.setText("Agregar");
        boton_agregar_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_objetoActionPerformed(evt);
            }
        });
        jPanel2.add(boton_agregar_objeto);
        boton_agregar_objeto.setBounds(290, 190, 100, 30);

        jLabel4.setText("Tipo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 190, 70, 30);

        txt_path_imagen.setEnabled(false);
        jPanel2.add(txt_path_imagen);
        txt_path_imagen.setBounds(80, 140, 190, 30);

        boton_path_imagen1.setText("Elegir");
        boton_path_imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_path_imagen1ActionPerformed(evt);
            }
        });
        jPanel2.add(boton_path_imagen1);
        boton_path_imagen1.setBounds(290, 140, 100, 30);
        jPanel2.add(txt_nombre_objeto);
        txt_nombre_objeto.setBounds(80, 90, 190, 30);

        jLabel2.setText("Path");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 140, 70, 30);

        jLabel3.setText("Nombre ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 90, 70, 30);

        jLabel1.setText("Meú de Carga de Objetos");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 310, 50);

        lista_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suelo", "Pared", "Goomba", "Koopa", "Ficha", "Hongo de vida", "Personaje Principal", "Castillo final" }));
        jPanel2.add(lista_tipo);
        lista_tipo.setBounds(80, 190, 190, 30);

        tablero2.addTab("Inicio", jPanel2);

        jPanel3.setLayout(null);

        panel_mostrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_mostrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_mostradorMouseClicked(evt);
            }
        });
        panel_mostrador.setLayout(null);
        jScrollPane2.setViewportView(panel_mostrador);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 880, 120);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        boton_borrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erick\\Desktop\\MarioMaker\\borrar.png")); // NOI18N
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarActionPerformed(evt);
            }
        });
        jPanel5.add(boton_borrar);
        boton_borrar.setBounds(20, 120, 100, 90);

        boton_editar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erick\\Desktop\\MarioMaker\\select.png")); // NOI18N
        boton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarActionPerformed(evt);
            }
        });
        jPanel5.add(boton_editar);
        boton_editar.setBounds(20, 10, 100, 90);

        jLabel12.setText("Modo");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 220, 90, 30);

        label_modo.setText("VER");
        jPanel5.add(label_modo);
        label_modo.setBounds(10, 250, 80, 40);

        jButton1.setText("Vision");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(50, 220, 90, 40);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(900, 10, 150, 310);

        panel_tablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_tableroMouseClicked(evt);
            }
        });
        panel_tablero.setLayout(null);
        jPanel3.add(panel_tablero);
        panel_tablero.setBounds(10, 140, 880, 510);

        label_tipo.setText("Tipo_objeto");
        jPanel3.add(label_tipo);
        label_tipo.setBounds(900, 350, 80, 40);

        nombre_objeto.setText("Objeto");
        jPanel3.add(nombre_objeto);
        nombre_objeto.setBounds(900, 320, 90, 30);

        boton_grafo_lista.setText("Grafo");
        boton_grafo_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_grafo_listaActionPerformed(evt);
            }
        });
        jPanel3.add(boton_grafo_lista);
        boton_grafo_lista.setBounds(970, 330, 80, 30);

        jLabel13.setText("No. Filas");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(900, 570, 70, 30);

        jLabel14.setText("No. Columnas");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(900, 610, 70, 20);

        label_no_columnas.setText("4");
        jPanel3.add(label_no_columnas);
        label_no_columnas.setBounds(970, 600, 80, 30);

        label_no_filas.setText("2");
        jPanel3.add(label_no_filas);
        label_no_filas.setBounds(970, 570, 80, 30);

        boton_add_fila.setText("Fila");
        boton_add_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_add_filaActionPerformed(evt);
            }
        });
        jPanel3.add(boton_add_fila);
        boton_add_fila.setBounds(900, 540, 70, 23);

        boton_add_columna.setText("Columna");
        boton_add_columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_add_columnaActionPerformed(evt);
            }
        });
        jPanel3.add(boton_add_columna);
        boton_add_columna.setBounds(980, 540, 73, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel15.setText("Selección Actual");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 10, 150, 30);

        jLabel16.setText("Fila");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 50, 50, 20);

        label_fila_actual.setText("0");
        jPanel4.add(label_fila_actual);
        label_fila_actual.setBounds(70, 50, 100, 20);

        label_columna_actual.setText("0");
        jPanel4.add(label_columna_actual);
        label_columna_actual.setBounds(70, 90, 100, 20);

        jLabel17.setText("Columna");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 90, 50, 20);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(900, 390, 190, 140);

        tablero2.addTab("Tablero", jPanel3);

        getContentPane().add(tablero2);
        tablero2.setBounds(0, 0, 1100, 690);

        setBounds(0, 0, 1124, 781);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_graficarActionPerformed
       mostrarGrafica();
      
    }//GEN-LAST:event_boton_graficarActionPerformed

    private void boton_agregar_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_objetoActionPerformed
        if((txt_nombre_objeto.getText().equals(""))||(txt_path_imagen.getText().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Debe llenar los datos del objeto");
        }else
        {
                agregar(lista_tipo.getSelectedIndex());
                txt_nombre_objeto.setText("");
                txt_path_imagen.setText("");
                Imagen_prueba.setIcon(null);
                this.repaint();
                try 
                {
                        lista_objetos.ImprimirLista("objetos");            
                } catch (IOException ex) 
                {
                Logger.getLogger(Menu_carga.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        ImprimirMuestra();

    }//GEN-LAST:event_boton_agregar_objetoActionPerformed

    private void boton_path_imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_path_imagen1ActionPerformed
    ElegirImagen();        // TODO add your handling code here:
    }//GEN-LAST:event_boton_path_imagen1ActionPerformed

    private void seleccion_pilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion_pilaActionPerformed
     if(seleccion_pila.isSelected())
     {
         seleccion_cola.setSelected(false);
     }
     else
     {
         seleccion_cola.setSelected(true);
     }
    }//GEN-LAST:event_seleccion_pilaActionPerformed

    private void seleccion_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion_colaActionPerformed
     if(seleccion_cola.isSelected())
     {
         seleccion_pila.setSelected(false);
     }
     else
     {
         seleccion_pila.setSelected(true);
     }
    }//GEN-LAST:event_seleccion_colaActionPerformed

    private void boton_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_continuarActionPerformed
        if(lista_objetos.Vacio())
        {
            JOptionPane.showMessageDialog(this, "Debe Agregar algun objeto a la lista.");
        }else
        {
           tablero2.enable(true);
           dibujarEnMostrador();
           JOptionPane.showMessageDialog(this, "Tablero Habilitado");
        }
        
    }//GEN-LAST:event_boton_continuarActionPerformed

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrarActionPerformed
        if(boton_borrar.isEnabled())
        {
            boton_editar.enable(true);
            boton_borrar.enable(false);
            label_modo.setText("BORRAR");
        }
    }//GEN-LAST:event_boton_borrarActionPerformed

    private void boton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_editarActionPerformed
        if(boton_editar.isEnabled())
        {
            boton_editar.enable(false);
            boton_borrar.enable(true);
            label_modo.setText("EDITAR");
        }

    }//GEN-LAST:event_boton_editarActionPerformed

    private void boton_grafo_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_grafo_listaActionPerformed

        //1 cola tipo_extraccion
        //0 Pila tipo_extraccion
        if(tipo_extraccion==0)
        {
            try {
                lista_objetos.ImprimirLista("Pila");
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
            try {
                lista_objetos.ImprimirLista("Cola");
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_boton_grafo_listaActionPerformed

    private void Imagen_pruebaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Imagen_pruebaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagen_pruebaKeyPressed

    private void Imagen_pruebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen_pruebaMouseClicked
        JOptionPane.showMessageDialog(this, "nombre");
    }//GEN-LAST:event_Imagen_pruebaMouseClicked

    private void panel_mostradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_mostradorMouseClicked
    Component[] lista_temporal=panel_mostrador.getComponents(); 
    //Generic[] lista_temporal=(Generic[]) panel_mostrador.getComponents(); 
    posicion_x=evt.getX();
    posicion_y=evt.getY();
    int numero=lista_objetos.tamanho();
    int ancho_bloque=panel_mostrador.getWidth()/numero;
    int altura_bloque=panel_mostrador.getHeight();
    for(int cont=0;cont<numero;cont++)
    {
        if((cont*ancho_bloque<=posicion_x)&&(posicion_x<=(cont*ancho_bloque+ancho_bloque)))
        {
            if(seleccion_cola.isSelected())
            {
                seleccionado=(Generic)lista_objetos.RCola(cont).dato;
            }
            else
            {
                seleccionado=(Generic)lista_objetos.RPila(cont).dato;
            }
           
            //Aque vemos que hace al elegirlo XD
            //VER ver, BORRAR borrar, EDITAR descolar/desapilar
            if(label_modo.getText().equals("VER"))
            {
                nombre_objeto.setText(seleccionado.nombre);
                String[] tipos={"Suelo","Pared","Goomba","Koopa","Ficha","Hongo","Personaje Principal","Castillo"};
                label_tipo.setText(tipos[seleccionado.tipo]);
            }
            if(label_modo.getText().equals("EDITAR"))
            {
                
            }
            if(label_modo.getText().equals("BORRAR"))
            {
            }
            
            
        }
    }
    
    //nombre_objeto.setText(;
    }//GEN-LAST:event_panel_mostradorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        label_modo.setText("VER");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panel_tableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_tableroMouseClicked
     int x=evt.getX();
     int y=evt.getY();
     int no_filas=Integer.valueOf(label_no_filas.getText());
     int no_columnas=Integer.valueOf(label_no_columnas.getText());
     int ancho=panel_tablero.getWidth();
     int altura=panel_tablero.getHeight();
     int ancho_casilla=ancho/no_columnas;
     int altura_casilla=altura/no_filas;
     for(int n=0;n<no_filas;n++)
     {
         for(int m=0;m<no_columnas;m++)
         {
             //(cont*ancho_bloque<=posicion_x)&&(posicion_x<=(cont*ancho_bloque+ancho_bloque))
            if((n*altura_casilla<=y)&&(y<=(n*altura_casilla+altura_casilla)))
            {
                if((m*ancho_casilla<=x)&&(x<=(m*ancho_casilla+ancho_casilla)))
                {
                        label_fila_actual.setText(String.valueOf(n+1));
                        label_columna_actual.setText(String.valueOf(m+1));
                }
              
            }
             
         }
     }
    }//GEN-LAST:event_panel_tableroMouseClicked

    private void boton_add_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_add_filaActionPerformed
        int fila=Integer.valueOf(label_no_filas.getText())+1;
        label_no_filas.setText(String.valueOf(fila));
    }//GEN-LAST:event_boton_add_filaActionPerformed

    private void boton_add_columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_add_columnaActionPerformed
        int columna=Integer.valueOf(label_no_columnas.getText())+1;
        label_no_columnas.setText(String.valueOf(columna));
    }//GEN-LAST:event_boton_add_columnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen_prueba;
    private javax.swing.JPanel JPanel_grafica;
    private javax.swing.JPanel Panel_muestra;
    private javax.swing.JPanel Panel_muestra1;
    private javax.swing.JButton boton_add_columna;
    private javax.swing.JButton boton_add_fila;
    private javax.swing.JButton boton_agregar_objeto;
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_continuar;
    private javax.swing.JButton boton_editar;
    private javax.swing.JButton boton_graficar;
    private javax.swing.JButton boton_grafo_lista;
    private javax.swing.JButton boton_path_imagen1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label_columna_actual;
    private javax.swing.JLabel label_fila_actual;
    private javax.swing.JLabel label_grafo;
    private javax.swing.JLabel label_modo;
    private javax.swing.JLabel label_no_columnas;
    private javax.swing.JLabel label_no_filas;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JComboBox lista_tipo;
    public static javax.swing.JLabel nombre_objeto;
    private javax.swing.JPanel panel_mostrador;
    private javax.swing.JPanel panel_tablero;
    private javax.swing.JRadioButton seleccion_cola;
    private javax.swing.JRadioButton seleccion_pila;
    private javax.swing.JTabbedPane tablero2;
    private javax.swing.JTextField txt_nombre_objeto;
    private javax.swing.JTextField txt_path_imagen;
    // End of variables declaration//GEN-END:variables
    public void ElegirImagen()
    {
            seleccion =new JFileChooser(this.PathActual());
            FileNameExtensionFilter filtro=new FileNameExtensionFilter("jpg","jpg","png","mbp");
            seleccion.setFileFilter(filtro);
            seleccion.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int resultado= seleccion.showOpenDialog(this);
            if(resultado==JFileChooser.APPROVE_OPTION){
            File nombre=seleccion.getSelectedFile();
            path=nombre.toString();
            String url=seleccion.getSelectedFile().getAbsolutePath();           
            this.setTitle(url);
        }
        //JOptionPane.showMessageDialog(this, path);
        mostrar_Prueba();
        txt_path_imagen.setText(path);
    }
    public void mostrar_Prueba()
    {
        int ancho_label=Imagen_prueba.getWidth();
        int altura_label=Imagen_prueba.getHeight();
        ImageIcon imagen = new ImageIcon(path); 
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_label, 
                                                               altura_label, 
                                                               Image.SCALE_DEFAULT));
                           Imagen_prueba.setIcon(icono);
    }
    public void graficar(){
    int ancho_label=Imagen_prueba.getWidth();
    int altura_label=Imagen_prueba.getHeight();
    //JLabel[][] objetos_tablero=new JLabel[altura][anchura];
    //int ancho_bloque=ancho_label/anchura;
    //int altura_bloque=altura_label/altura;
//    
//        for(int x=0;x<anchura;x++){
//            for(int y=0;y<altura;y++){
//                 String url=buscar(tablero[x][y]);
//                  jLabel1 = new javax.swing.JLabel();
//                  jLabel1.setBounds(ancho_bloque*x, altura_bloque*y,ancho_bloque,altura_bloque );
//                  ImageIcon imagen = new ImageIcon(url); 
//                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_bloque, 
//                                                               altura_bloque, 
//                                                               Image.SCALE_DEFAULT));
//                           jLabel1.setIcon(icono);
//                           objetos_tablero[x][y]=jLabel1;
////                           nuevo.add(this.Juego);
//                           Juego.add(objetos_tablero[x][y]);
//                          
//                           Juego.repaint();
//                           jLabel1.repaint();
//                           
//                           if(encontrado==true){
//                               
//                           System.out.println(x +","+y);
//                           x_heroe=x;
//                           y_heroe=y;
//                           encontrado=false;
//                           }
//                         
//                  
//                  
//            }
//
//        }
//    Ejecutable nuevo=new Ejecutable();
//    nuevo.show(true);
//    nuevo.setLayout(null);
//     nuevo.objetos=objetos_tablero;   
    }
    public void agregar(int tipo)
    {
        // 1. Suelo
        // 2. Pared
        // 3. Goomba
        // 4. Koopa
        // 5. Ficha
        // 6. Hongo
        // 7. Personaje
        // 8. Castillo
                    if(tipo==0)
                    {
                        no_suelo++;
                    }
                    if(tipo==1)
                    {
                        no_pared++;
                    }
                    if(tipo==2)
                    {
                        no_goomba++;
                    }
                    if(tipo==3)
                    {
                        no_koopa++;
                    }
                    if(tipo==4)
                    {
                        no_ficha++;
                    }
                    if(tipo==5)
                    {
                        no_hongo++;
                    }
                    if(tipo==6)
                    {
                        if(no_personaje!=0)
                        {
                            JOptionPane.showMessageDialog(this, "Ya hay un heróe en la lista.");
                        }
                        else
                        {
                            String nombre=txt_nombre_objeto.getText();
                            String path=txt_path_imagen.getText();
                            int tipo_temp=lista_tipo.getSelectedIndex();
                            tablero.lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                            lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                            no_personaje++;
                        }
                    }
                    else
                    {
                        if(tipo==7)
                        {
                            if(no_castillo!=0)
                            {
                                JOptionPane.showMessageDialog(this, "Ya hay un castillo en la lista.");
                            }
                            else 
                            {
                                String nombre=txt_nombre_objeto.getText();
                                String path=txt_path_imagen.getText();
                                int tipo_temp=lista_tipo.getSelectedIndex();
                                lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                                no_castillo++;
                            }
                        }
                        else 
                        {
                                String nombre=txt_nombre_objeto.getText();
                                String path=txt_path_imagen.getText();
                                int tipo_temp=lista_tipo.getSelectedIndex();
                                lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                        }
                    }

                    
                    


      
    }
    public void mostrarGrafica()
    {
//        Ajustar el tama;o de la imagen.
        int ancho_label=label_grafo.getWidth();
        int altura_label=label_grafo.getHeight();
        ImageIcon imagen = new ImageIcon(PathActual()+"\\"+"objetos.png"); 
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_label, 
                                                               altura_label, 
                                                               Image.SCALE_SMOOTH));
                           label_grafo.setIcon(icono);
        
//        ImageIcon imagen = new ImageIcon(PathActual()+"\\"+"objetos.png");
//        Icon icono = new ImageIcon(imagen.getImage());
//        label_grafo.setIcon(icono);
//        label_grafo.repaint();
                
    }
    public String PathActual()
    {
    String path="";
     File miDir = new File (".");
     try 
     {
         path=miDir.getCanonicalPath();
     }
     catch(Exception e) 
     {
       e.printStackTrace();
     }
     return path;
    }
    
    public void ImprimirMuestra()
    {
        int ancho=Panel_muestra1.getHeight();
        int altura=Panel_muestra1.getWidth();
        Lista temporal=lista_objetos.clonar();
        Panel_muestra.removeAll();
        Panel_muestra.setLayout(null);
        int contador=0;
//        while(!temporal.Vacio())
//        {
//            contador++;
//            Nodo nuevo=temporal.ExtraerCabeza();
//            Generic objeto_temporal= (Generic)nuevo.dato;
//            String nombre=objeto_temporal.nombre;
//            String[] tipos={"Suelo","Pared","Goomba","Koopa","Ficha","Hongo","Personaje Principal","Castillo"};
//            String tipo=tipos[objeto_temporal.tipo];
//            String path=objeto_temporal.icono_path;
//            //jLabel8.setBounds(10, 10, 90, 30);
//            //(x,y,ancho,altura)
//            JLabel mnombre= new JLabel(); mnombre.setText(nombre);Panel_muestra.add(mnombre); mnombre.setBounds( 100*contador,100*contador,100*contador,100*contador);    
//        }
        this.repaint();
//        String nombre=nuevo.nombre;
//        String tipo=nuevo.tipo;
//        String paht=nuevo.pathimagen;
//        int  ataque=nuevo.ataque;
//        int defensa=nuevo.defensa;
//        Mostrador.setLayout(null);
//        JLabel mnombre= new JLabel(); mnombre.setText(nombre);Mostrador.add(mnombre); mnombre.setBounds(120,mostradory,130,30);
//        JLabel mataque= new JLabel(); mataque.setText(String.valueOf(ataque));Mostrador.add(mataque); mataque.setBounds(270,mostradory,130,30);
//        JLabel mdefensa=new JLabel(); mdefensa.setText(String.valueOf(defensa)); Mostrador.add(mdefensa);mdefensa.setBounds(410,mostradory,130,30);
//        JLabel mtipo= new JLabel(); mtipo.setText(tipo);Mostrador.add(mtipo); mtipo.setBounds(560,mostradory,130,30);
//        JButton eliminar=new JButton(); eliminar.setText("Eliminar");Mostrador.add(eliminar); eliminar.setBounds(690,mostradory,100,20);
//        JButton modificar=new JButton(); modificar.setText("Modificar");Mostrador.add(modificar);modificar.setBounds(690,mostradory+20,100,20);
//        JLabel mimagen=new JLabel();Mostrador.add(mimagen);mimagen.setBounds(10,mostradory+20,100,100);
//        ImageIcon imagen = new ImageIcon(pathactual);
//        ImageIcon imagenredimencionada= new ImageIcon(imagen.getImage().getScaledInstance(100, 100,0));
//        mimagen.setIcon(imagenredimencionada);
//        mostradory+=100;
    }
    public void pasarTablero()
    {
       //1 cola tipo_extraccion
       //0 Pila tipo_extraccion
       if(seleccion_pila.isSelected())
       {
           tipo_extraccion=0;
           cola_resultante=lista_objetos.clonarcola();  
           
       }else
       {
           tipo_extraccion=1;
           pila_resultante=lista_objetos.clonarpila();
       }
             
       tablero.show(true);
       
       
    }
    public void dibujarEnMostrador()
    {
       
        panel_mostrador.removeAll();
        int numero=lista_objetos.tamanho();
        int ancho_bloque=panel_mostrador.getWidth()/numero;
        int altura_bloque=panel_mostrador.getHeight();
        //JPanel[] lista_paneles=new JPanel[numero];
        if(seleccion_cola.isSelected())
        {
            Nodo temporal=lista_objetos.cola;
            for(int x=0;x<numero;x++)
            {
                Generic obj_temporal=(Generic)temporal.dato;
               
                ImageIcon imagen=new ImageIcon(obj_temporal.icono_path);
                Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ancho_bloque, altura_bloque, Image.SCALE_DEFAULT));
                obj_temporal.setIcon(icono);
                panel_mostrador.add(obj_temporal);
                obj_temporal.setBounds((ancho_bloque*x),0, ancho_bloque, altura_bloque);
                obj_temporal.repaint();
           //     obj_temporal.addMouseListener((MouseListener) this);
                panel_mostrador.repaint();
                temporal=temporal.siguiente;
            }
        }
        if(seleccion_pila.isSelected())
        {
                Nodo temporal=lista_objetos.cabeza;
                for(int x=0;x<numero;x++)
                {
                    Generic obj_temporal=(Generic)temporal.dato;

                    ImageIcon imagen=new ImageIcon(obj_temporal.icono_path);
                    Icon icono=new ImageIcon(imagen.getImage().getScaledInstance(ancho_bloque, altura_bloque, Image.SCALE_DEFAULT));
                    obj_temporal.setIcon(icono);
                    panel_mostrador.add(obj_temporal);
                    obj_temporal.setBounds((ancho_bloque*x),0, ancho_bloque, altura_bloque);
                    obj_temporal.repaint();
                    panel_mostrador.repaint();
                    temporal=temporal.anterior;
                }
        }
        
        
    }
    
    
    public void mouseEntered(MouseEvent evento) {
        if (evento.getSource() == null){
         nombre_objeto.setText("Entro a mi botón");
         label_tipo.setText("");
        }      
       }
}
