/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import Estructuras.Cola;
import Estructuras.Generic;
import Estructuras.Lista;
import Estructuras.Pila;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick
 */
public class Menu_carga extends javax.swing.JFrame {

    /**
     * Creates new form Menu_inicio
     */
    public JFileChooser seleccion;
    public static String path;
    public File archivo;
    public FileReader fr;
    public  BufferedReader br;
    
    public static int no_suelo=0;
    public static int no_pared=0;
    public static int no_goomba=0;
    public static int no_koopa=0;
    public static int no_ficha=0;
    public static int no_hongo=0;
    public static int no_personaje=0;
    public static int no_castillo=0;
    public static Lista lista_objetos =new Lista();
    public Generic objeto_nuevo;
    public static int tipo_extraccion=0;
    public static Pila pila_resultante;
    public static Cola cola_resultante;
    //1 cola tipo_extraccion
    //0 Pila tipo_extraccion
    
    
    
    public Menu_carga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_objeto = new javax.swing.JTextField();
        txt_path_imagen = new javax.swing.JTextField();
        boton_agregar_objeto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lista_tipo = new javax.swing.JComboBox();
        boton_path_imagen1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel_muestra1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel_muestra = new javax.swing.JPanel();
        JPanel_grafica = new javax.swing.JPanel();
        label_grafo = new javax.swing.JLabel();
        boton_graficar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Imagen_prueba = new javax.swing.JLabel();
        boton_continuar = new javax.swing.JButton();
        seleccion_pila = new javax.swing.JRadioButton();
        seleccion_cola = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mario Maker Guatemalteco v.1.0.0");
        getContentPane().setLayout(null);

        jLabel1.setText("Meú de Carga de Objetos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 140, 40);

        jLabel2.setText("Path");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 70, 30);

        jLabel3.setText("Nombre ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 70, 30);
        getContentPane().add(txt_nombre_objeto);
        txt_nombre_objeto.setBounds(90, 60, 190, 30);

        txt_path_imagen.setEnabled(false);
        getContentPane().add(txt_path_imagen);
        txt_path_imagen.setBounds(90, 110, 190, 30);

        boton_agregar_objeto.setText("Agregar");
        boton_agregar_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_objetoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_agregar_objeto);
        boton_agregar_objeto.setBounds(290, 180, 100, 30);

        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 70, 30);

        lista_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suelo", "Pared", "Goomba", "Koopa", "Ficha", "Hongo de vida", "Personaje Principal", "Castillo final" }));
        getContentPane().add(lista_tipo);
        lista_tipo.setBounds(90, 180, 190, 30);

        boton_path_imagen1.setText("Elegir");
        boton_path_imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_path_imagen1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton_path_imagen1);
        boton_path_imagen1.setBounds(290, 110, 100, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Panel_muestra1.setLayout(null);

        jLabel8.setText("Nombre");
        Panel_muestra1.add(jLabel8);
        jLabel8.setBounds(30, 70, 90, 30);

        jLabel9.setText("Path");
        Panel_muestra1.add(jLabel9);
        jLabel9.setBounds(140, 70, 220, 30);

        jLabel10.setText("Imagen");
        Panel_muestra1.add(jLabel10);
        jLabel10.setBounds(360, 70, 110, 30);

        jLabel11.setText("Tipo");
        Panel_muestra1.add(jLabel11);
        jLabel11.setBounds(520, 70, 100, 30);

        Panel_muestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_muestra1.add(Panel_muestra);
        Panel_muestra.setBounds(20, 110, 720, 320);

        jScrollPane1.setViewportView(Panel_muestra1);

        jTabbedPane1.addTab("Lista", jScrollPane1);

        JPanel_grafica.setLayout(null);
        JPanel_grafica.add(label_grafo);
        label_grafo.setBounds(20, 70, 740, 370);

        boton_graficar.setText("Gráficar");
        boton_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_graficarActionPerformed(evt);
            }
        });
        JPanel_grafica.add(boton_graficar);
        boton_graficar.setBounds(10, 10, 130, 30);

        jTabbedPane1.addTab("Gráfica", JPanel_grafica);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 230, 780, 480);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 220, 120, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel6.setText("Vista Previa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 120, 130, 20);
        jPanel1.add(Imagen_prueba);
        Imagen_prueba.setBounds(140, 10, 180, 110);

        boton_continuar.setText("Continuar");
        boton_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_continuarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_continuar);
        boton_continuar.setBounds(210, 173, 120, 40);

        seleccion_pila.setSelected(true);
        seleccion_pila.setText("Pila");
        seleccion_pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion_pilaActionPerformed(evt);
            }
        });
        jPanel1.add(seleccion_pila);
        seleccion_pila.setBounds(30, 140, 120, 30);

        seleccion_cola.setText("Cola");
        seleccion_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion_colaActionPerformed(evt);
            }
        });
        jPanel1.add(seleccion_cola);
        seleccion_cola.setBounds(30, 180, 130, 30);

        jLabel7.setText("Elija tipo de Extracción");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 100, 150, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(430, 10, 350, 230);

        setBounds(0, 0, 822, 781);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_graficarActionPerformed
       mostrarGrafica();
      
    }//GEN-LAST:event_boton_graficarActionPerformed

    private void boton_agregar_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_objetoActionPerformed
        if((txt_nombre_objeto.getText().equals(""))||(txt_path_imagen.getText().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Debe llenar los datos del objeto");
        }else
        {
                agregar(lista_tipo.getSelectedIndex());
                txt_nombre_objeto.setText("");
                txt_path_imagen.setText("");
                Imagen_prueba.setIcon(null);
                this.repaint();
                try 
                {
                        lista_objetos.ImprimirLista("objetos");            
                } catch (IOException ex) 
                {
                Logger.getLogger(Menu_carga.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        ImprimirMuestra();

    }//GEN-LAST:event_boton_agregar_objetoActionPerformed

    private void boton_path_imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_path_imagen1ActionPerformed
    ElegirImagen();        // TODO add your handling code here:
    }//GEN-LAST:event_boton_path_imagen1ActionPerformed

    private void seleccion_pilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion_pilaActionPerformed
     if(seleccion_pila.isSelected())
     {
         seleccion_cola.setSelected(false);
     }
     else
     {
         seleccion_cola.setSelected(true);
     }
    }//GEN-LAST:event_seleccion_pilaActionPerformed

    private void seleccion_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion_colaActionPerformed
     if(seleccion_cola.isSelected())
     {
         seleccion_pila.setSelected(false);
     }
     else
     {
         seleccion_pila.setSelected(true);
     }
    }//GEN-LAST:event_seleccion_colaActionPerformed

    private void boton_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_continuarActionPerformed
        if(lista_objetos.Vacio())
        {
            JOptionPane.showMessageDialog(this, "Debe Agregar algun objeto a la lista.");
        }else
        {
            pasarTablero();
        }
        
    }//GEN-LAST:event_boton_continuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen_prueba;
    private javax.swing.JPanel JPanel_grafica;
    private javax.swing.JPanel Panel_muestra;
    private javax.swing.JPanel Panel_muestra1;
    private javax.swing.JButton boton_agregar_objeto;
    private javax.swing.JButton boton_continuar;
    private javax.swing.JButton boton_graficar;
    private javax.swing.JButton boton_path_imagen1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_grafo;
    private javax.swing.JComboBox lista_tipo;
    private javax.swing.JRadioButton seleccion_cola;
    private javax.swing.JRadioButton seleccion_pila;
    private javax.swing.JTextField txt_nombre_objeto;
    private javax.swing.JTextField txt_path_imagen;
    // End of variables declaration//GEN-END:variables
    public void ElegirImagen()
    {
            seleccion =new JFileChooser("Z:\\Descarga");
            FileNameExtensionFilter filtro=new FileNameExtensionFilter("jpg","jpg","png","mbp");
            seleccion.setFileFilter(filtro);
            seleccion.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int resultado= seleccion.showOpenDialog(this);
            if(resultado==JFileChooser.APPROVE_OPTION){
            File nombre=seleccion.getSelectedFile();
            path=nombre.toString();
            String url=seleccion.getSelectedFile().getAbsolutePath();           
            this.setTitle(url);
        }
        //JOptionPane.showMessageDialog(this, path);
        mostrar_Prueba();
        txt_path_imagen.setText(path);
    }
    public void mostrar_Prueba()
    {
        int ancho_label=Imagen_prueba.getWidth();
        int altura_label=Imagen_prueba.getHeight();
        ImageIcon imagen = new ImageIcon(path); 
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_label, 
                                                               altura_label, 
                                                               Image.SCALE_DEFAULT));
                           Imagen_prueba.setIcon(icono);
    }
    public void graficar(){
    int ancho_label=Imagen_prueba.getWidth();
    int altura_label=Imagen_prueba.getHeight();
    //JLabel[][] objetos_tablero=new JLabel[altura][anchura];
    //int ancho_bloque=ancho_label/anchura;
    //int altura_bloque=altura_label/altura;
//    
//        for(int x=0;x<anchura;x++){
//            for(int y=0;y<altura;y++){
//                 String url=buscar(tablero[x][y]);
//                  jLabel1 = new javax.swing.JLabel();
//                  jLabel1.setBounds(ancho_bloque*x, altura_bloque*y,ancho_bloque,altura_bloque );
//                  ImageIcon imagen = new ImageIcon(url); 
//                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_bloque, 
//                                                               altura_bloque, 
//                                                               Image.SCALE_DEFAULT));
//                           jLabel1.setIcon(icono);
//                           objetos_tablero[x][y]=jLabel1;
////                           nuevo.add(this.Juego);
//                           Juego.add(objetos_tablero[x][y]);
//                          
//                           Juego.repaint();
//                           jLabel1.repaint();
//                           
//                           if(encontrado==true){
//                               
//                           System.out.println(x +","+y);
//                           x_heroe=x;
//                           y_heroe=y;
//                           encontrado=false;
//                           }
//                         
//                  
//                  
//            }
//
//        }
//    Ejecutable nuevo=new Ejecutable();
//    nuevo.show(true);
//    nuevo.setLayout(null);
//     nuevo.objetos=objetos_tablero;   
    }
    public void agregar(int tipo)
    {
        // 1. Suelo
        // 2. Pared
        // 3. Goomba
        // 4. Koopa
        // 5. Ficha
        // 6. Hongo
        // 7. Personaje
        // 8. Castillo
                    if(tipo==0)
                    {
                        no_suelo++;
                    }
                    if(tipo==1)
                    {
                        no_pared++;
                    }
                    if(tipo==2)
                    {
                        no_goomba++;
                    }
                    if(tipo==3)
                    {
                        no_koopa++;
                    }
                    if(tipo==4)
                    {
                        no_ficha++;
                    }
                    if(tipo==5)
                    {
                        no_hongo++;
                    }
                    if(tipo==6)
                    {
                        if(no_personaje!=0)
                        {
                            JOptionPane.showMessageDialog(this, "Ya hay un heróe en la lista.");
                        }
                        else
                        {
                            String nombre=txt_nombre_objeto.getText();
                            String path=txt_path_imagen.getText();
                            int tipo_temp=lista_tipo.getSelectedIndex();
                            lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                            no_personaje++;
                        }
                    }
                    else
                    {
                        if(tipo==7)
                        {
                            if(no_castillo!=0)
                            {
                                JOptionPane.showMessageDialog(this, "Ya hay un castillo en la lista.");
                            }
                            else 
                            {
                                String nombre=txt_nombre_objeto.getText();
                                String path=txt_path_imagen.getText();
                                int tipo_temp=lista_tipo.getSelectedIndex();
                                lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                                no_castillo++;
                            }
                        }
                        else 
                        {
                                String nombre=txt_nombre_objeto.getText();
                                String path=txt_path_imagen.getText();
                                int tipo_temp=lista_tipo.getSelectedIndex();
                                lista_objetos.InsertarAlFrente(this.objeto_nuevo=new Generic(nombre,path,tipo_temp));
                        }
                    }

                    
                    


      
    }
    public void mostrarGrafica()
    {
//        Ajustar el tama;o de la imagen.
        int ancho_label=label_grafo.getWidth();
        int altura_label=label_grafo.getHeight();
        ImageIcon imagen = new ImageIcon(PathActual()+"\\"+"objetos.png"); 
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ancho_label, 
                                                               altura_label, 
                                                               Image.SCALE_SMOOTH));
                           label_grafo.setIcon(icono);
        
//        ImageIcon imagen = new ImageIcon(PathActual()+"\\"+"objetos.png");
//        Icon icono = new ImageIcon(imagen.getImage());
//        label_grafo.setIcon(icono);
//        label_grafo.repaint();
                
    }
    public String PathActual()
    {
    String path="";
     File miDir = new File (".");
     try 
     {
         path=miDir.getCanonicalPath();
     }
     catch(Exception e) 
     {
       e.printStackTrace();
     }
     return path;
    }
    
    public void ImprimirMuestra()
    {
        int ancho=Panel_muestra1.getHeight();
        int altura=Panel_muestra1.getWidth();
        Lista temporal=lista_objetos.clonar();
        Panel_muestra.removeAll();
        Panel_muestra.setLayout(null);
        int contador=0;
//        while(!temporal.Vacio())
//        {
//            contador++;
//            Nodo nuevo=temporal.ExtraerCabeza();
//            Generic objeto_temporal= (Generic)nuevo.dato;
//            String nombre=objeto_temporal.nombre;
//            String[] tipos={"Suelo","Pared","Goomba","Koopa","Ficha","Hongo","Personaje Principal","Castillo"};
//            String tipo=tipos[objeto_temporal.tipo];
//            String path=objeto_temporal.icono_path;
//            //jLabel8.setBounds(10, 10, 90, 30);
//            //(x,y,ancho,altura)
//            JLabel mnombre= new JLabel(); mnombre.setText(nombre);Panel_muestra.add(mnombre); mnombre.setBounds( 100*contador,100*contador,100*contador,100*contador);    
//        }
        this.repaint();
//        String nombre=nuevo.nombre;
//        String tipo=nuevo.tipo;
//        String paht=nuevo.pathimagen;
//        int  ataque=nuevo.ataque;
//        int defensa=nuevo.defensa;
//        Mostrador.setLayout(null);
//        JLabel mnombre= new JLabel(); mnombre.setText(nombre);Mostrador.add(mnombre); mnombre.setBounds(120,mostradory,130,30);
//        JLabel mataque= new JLabel(); mataque.setText(String.valueOf(ataque));Mostrador.add(mataque); mataque.setBounds(270,mostradory,130,30);
//        JLabel mdefensa=new JLabel(); mdefensa.setText(String.valueOf(defensa)); Mostrador.add(mdefensa);mdefensa.setBounds(410,mostradory,130,30);
//        JLabel mtipo= new JLabel(); mtipo.setText(tipo);Mostrador.add(mtipo); mtipo.setBounds(560,mostradory,130,30);
//        JButton eliminar=new JButton(); eliminar.setText("Eliminar");Mostrador.add(eliminar); eliminar.setBounds(690,mostradory,100,20);
//        JButton modificar=new JButton(); modificar.setText("Modificar");Mostrador.add(modificar);modificar.setBounds(690,mostradory+20,100,20);
//        JLabel mimagen=new JLabel();Mostrador.add(mimagen);mimagen.setBounds(10,mostradory+20,100,100);
//        ImageIcon imagen = new ImageIcon(pathactual);
//        ImageIcon imagenredimencionada= new ImageIcon(imagen.getImage().getScaledInstance(100, 100,0));
//        mimagen.setIcon(imagenredimencionada);
//        mostradory+=100;
    }
    public void pasarTablero()
    {
       //1 cola tipo_extraccion
       //0 Pila tipo_extraccion
       if(seleccion_pila.isSelected())
       {
           tipo_extraccion=0;
           cola_resultante=lista_objetos.clonarcola();  
           
       }else
       {
           tipo_extraccion=1;
           pila_resultante=lista_objetos.clonarpila();
       }
       
       Tablero nuevo=new Tablero();
       nuevo.show(true);
       nuevo.CargarLista(lista_objetos);
       
    }
    
}
