/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import Estructuras.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Erick
 */

public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Lista lista=new Lista();
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        boton_borrar = new javax.swing.JButton();
        boton_editar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_modo = new javax.swing.JLabel();
        boton_grafo_lista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MarioMaker v.1.0.0");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 680, 120);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        boton_borrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erick\\Desktop\\MarioMaker\\borrar.png")); // NOI18N
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_borrar);
        boton_borrar.setBounds(20, 120, 100, 90);

        boton_editar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erick\\Desktop\\MarioMaker\\select.png")); // NOI18N
        boton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_editar);
        boton_editar.setBounds(20, 10, 100, 90);

        jLabel1.setText("Modo");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 220, 90, 30);

        label_modo.setText("Editor");
        jPanel2.add(label_modo);
        label_modo.setBounds(10, 250, 110, 40);

        boton_grafo_lista.setText("Grafo");
        boton_grafo_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_grafo_listaActionPerformed(evt);
            }
        });
        jPanel2.add(boton_grafo_lista);
        boton_grafo_lista.setBounds(70, 230, 59, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(700, 10, 150, 310);

        setBounds(0, 0, 876, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_editarActionPerformed
     if(boton_editar.isEnabled())
     {
         boton_editar.enable(false);
         boton_borrar.enable(true);
         label_modo.setText("EDITAR");
     }

     
    }//GEN-LAST:event_boton_editarActionPerformed

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrarActionPerformed
     if(boton_borrar.isEnabled())
     {
         boton_editar.enable(true);
         boton_borrar.enable(false);
         label_modo.setText("BORRAR");
     }

    }//GEN-LAST:event_boton_borrarActionPerformed

    private void boton_grafo_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_grafo_listaActionPerformed

        //1 cola tipo_extraccion
       //0 Pila tipo_extraccion
        if(Menu_carga.tipo_extraccion==0)
        {
            try {
                lista.ImprimirLista("Pila");
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
            try {
                lista.ImprimirLista("Cola");
            } catch (IOException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_boton_grafo_listaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_editar;
    private javax.swing.JButton boton_grafo_lista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_modo;
    // End of variables declaration//GEN-END:variables
    public void CargarLista(Lista nueva)
    {
        lista=nueva;
    }
}
